#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TORCH_INCLUDES=$(python3 -c "
import torch.utils.cpp_extension as e
for p in e.include_paths():
    print(f'    - -I{p}')
")

CUDA_HOME="${CUDA_HOME:-${CUDA_PATH:-/usr/local/cuda}}"

cat > "$REPO_ROOT/.clangd" <<EOF
# clangd config for C++/CUDA in this project (Zed/VSCode LSP: go-to-def, hover, etc.)
# Auto-generated by scripts/gen_clangd.sh — do not edit by hand.
---
CompileFlags:
  Add:
    - -std=c++17
    - -Icsrc
$TORCH_INCLUDES
    - -I${CUDA_HOME}/include
    - -xcuda
    - --cuda-host-only
    - --cuda-path=${CUDA_HOME}
Diagnostics:
  MissingIncludes: None
  UnusedIncludes: None

If:
  PathMatch: .*\\.cu$
EOF

echo "Written .clangd (CUDA_HOME=${CUDA_HOME})"
